[package]
name = "basic_glfw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { version = "1.0.69", features = ["parallel"] }
libc = "0.2.100"
bindgen = "0.59.1"